version: '3'
services:
    app:
        build: ./ #builds image from Dockerfile in current directory
        command: pnpm run dev --host
        ports:
            - 8080:8080 #change to needed port
        volumes:
            - ./:/app/
            - nodemodules:/app/node_modules #volume for nodue modules to prevent host overwrite

volumes:
    nodemodules: {}